version: '3.8'
services:
  db:
    image: postgres:13
    container_name: futureboostify_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: futureboostify
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - futureboostify_network

  app:
    build:
      context: .
    image: futureboostify
    container_name: futureboostify_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/futureboostify
      SPRING_DATASOURCE_USERNAME: futureboostify
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - futureboostify_network

volumes:
  db_data:

networks:
  futureboostify_network:
