# Use the official OpenJDK image as a parent image
FROM adoptopenjdk:11-jre-hotspot

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container at /app
COPY target/futureboostify.jar /app/futureboostify.jar

# Specify the command to run your application
CMD ["java", "-jar", "futureboostify.jar"]
